name: Update README for Dark Mode

on:
  push:
    branches:
      - main  # adjust this branch name if necessary

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use github-readme-dark-mode
        uses: michaljach/github-readme-dark-mode@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
